#ifndef __MEM_MAA_RMW_OPPORTUNITY_PROFILER_HH__
#define __MEM_MAA_RMW_OPPORTUNITY_PROFILER_HH__

#include <algorithm>
#include <array>
#include <cstddef>
#include <cstdint>
#include <list>
#include <unordered_set>
#include <vector>

namespace gem5
{

/**
 * Non-functional shadow model for a bounded, four-way RMW delta buffer.
 *
 * The profiler never changes requests or data. It records only integer
 * ADD/MIN/MAX candidates selected by the caller and resets at each instruction
 * boundary, which makes its counts a conservative within-instruction
 * opportunity estimate rather than an unsafe cross-instruction claim.
 */
class RMWOpportunityProfiler
{
  public:
    static constexpr std::size_t EntryBytes = 80;
    static constexpr std::size_t Ways = 4;
    static constexpr std::array<std::size_t, 4> ByteBudgets = {
        4 * 1024, 8 * 1024, 16 * 1024, 32 * 1024};

    struct CacheSummary
    {
        std::size_t capacityLines = 0;
        uint64_t hits = 0;
        uint64_t misses = 0;
        uint64_t evictions = 0;
    };

    struct Summary
    {
        uint64_t totalUpdates = 0;
        uint64_t eligibleUpdates = 0;
        uint64_t baselineRequests = 0;
        std::size_t uniqueWords = 0;
        std::size_t uniqueLines = 0;
        std::array<CacheSummary, ByteBudgets.size()> caches{};
    };

  private:
    class SetAssociativeCache
    {
      private:
        std::size_t numSets;
        std::vector<std::list<uint64_t>> sets;
        uint64_t hits = 0;
        uint64_t misses = 0;
        uint64_t evictions = 0;

      public:
        explicit SetAssociativeCache(std::size_t byteBudget)
          : numSets(std::max<std::size_t>(1,
                (byteBudget / EntryBytes) / Ways)),
            sets(numSets)
        {
        }

        void reset()
        {
            for (auto &set : sets)
                set.clear();
            hits = misses = evictions = 0;
        }

        void access(uint64_t lineAddress)
        {
            auto &set = sets[(lineAddress >> 6) % numSets];
            const auto hit = std::find(set.begin(), set.end(), lineAddress);
            if (hit != set.end()) {
                hits++;
                set.splice(set.begin(), set, hit);
                return;
            }

            misses++;
            if (set.size() == Ways) {
                set.pop_back();
                evictions++;
            }
            set.push_front(lineAddress);
        }

        CacheSummary summary() const
        {
            return CacheSummary{numSets * Ways, hits, misses, evictions};
        }
    };

    bool profilingEnabled = false;
    uint64_t totalUpdates = 0;
    uint64_t eligibleUpdates = 0;
    uint64_t baselineRequests = 0;
    std::unordered_set<uint64_t> uniqueWords;
    std::unordered_set<uint64_t> uniqueLines;
    std::array<SetAssociativeCache, ByteBudgets.size()> caches = {
        SetAssociativeCache(ByteBudgets[0]),
        SetAssociativeCache(ByteBudgets[1]),
        SetAssociativeCache(ByteBudgets[2]),
        SetAssociativeCache(ByteBudgets[3])};

  public:
    explicit RMWOpportunityProfiler(bool enabled = false)
      : profilingEnabled(enabled)
    {
    }

    void setEnabled(bool enabled)
    {
        profilingEnabled = enabled;
        reset();
    }

    bool enabled() const { return profilingEnabled; }

    void reset()
    {
        totalUpdates = eligibleUpdates = baselineRequests = 0;
        uniqueWords.clear();
        uniqueLines.clear();
        for (auto &cache : caches)
            cache.reset();
    }

    /** Record one ReadEx generated by the unmodified row-table path. */
    void observeBaselineRequest()
    {
        if (profilingEnabled)
            baselineRequests++;
    }

    void observe(uint64_t wordAddress, bool eligible)
    {
        if (!profilingEnabled)
            return;

        totalUpdates++;
        if (!eligible)
            return;

        eligibleUpdates++;
        const uint64_t lineAddress = wordAddress & ~uint64_t(63);
        uniqueWords.insert(wordAddress);
        uniqueLines.insert(lineAddress);
        for (auto &cache : caches)
            cache.access(lineAddress);
    }

    Summary summary() const
    {
        Summary result;
        result.totalUpdates = totalUpdates;
        result.eligibleUpdates = eligibleUpdates;
        result.baselineRequests = baselineRequests;
        result.uniqueWords = uniqueWords.size();
        result.uniqueLines = uniqueLines.size();
        for (std::size_t i = 0; i < caches.size(); ++i)
            result.caches[i] = caches[i].summary();
        return result;
    }
};

} // namespace gem5

#endif // __MEM_MAA_RMW_OPPORTUNITY_PROFILER_HH__
