Import('*')

SimObject(
    'LANLMAA.py',
    sim_objects=[
        'LANLMAA',
        'LANLMAAControlSequencer',
        'LANLMAAControlTester',
    ],
    enums=['LANLMAAUpdateOperation'],
)
Source('lanl_maa.cc')
Source('control_sequencer.cc')
Source('control_tester.cc')

DebugFlag('LANLMAA')
